### ISSUE TITLE
Is there any activity on Quasar v1(.0.5) snippet implementation?

### ISSUE THREAD

**Issue by tpoth** [Abdelaziz18003/vscode-quasar-snippets#17]
In other word's, would you like to get any support in doing these snippets? Furthermore, do you any cooperation with @syflex to get this done?
Regards Thomas

**Comment by syflex** [comment]
Hello.
Thank you for checking in.

I will be rolling out a lot of updates by the weekend.

And I will love it if you will contribute.

I've got one other developer that will join by the weekend.

Thank you again.

Please you can mail me for any direction you think is better.

**Comment by Abdelaziz18003** [comment]
Hi @thompoth @syflex ,

Few days ago I started adding snippets of quasar@1.0.5 new components. I expect to release the new version of the extension (v1.0.0) in few days after:

- Adding all new components (nearly done).
- Checking the old components snippets and edit them according to the new doc.
- re-ordering the snippets according to the documentation.

and Yes, I will appreciate any support to help speeding up the release.

This is the first contact between me and @syflex , and I appreciate any contribution or suggestion from him.

I thank you both for being interested, and I welcome any contribution.

**Comment by tpoth** [comment]
Hi Guys @Abdelaziz18003 @syflex ,
thx for your feedback.
Is there any coordination for the "open jobs"?
What would be the most important things to do these days?

Regards

**Comment by Abdelaziz18003** [comment]
Hi @thompoth , Thanks for your interest.
If you are interested in contributing, the most important things to do these days are adding missing components, and updating existing ones according to the new documentation.
My work progress right now is in `QChatMessage` (following the doc order). You can start adding/updating components starting from there (create an issue to indicate what are you going to work on, to avoid working on the same things). And please don't forget to read the contribution guide on the home page to keep things consistent and I am available if you need any help.

Regards.

**Comment by tpoth** [comment]
Hi,
i updated my Avatar and username in GitHub, just to mention :-)

Ok, thanks for your support.
I'll be go through the contribution guide and afterwards i'll grab the forms section, as this is my personal need these days. As soon as i start doing the forms components I'll open an Issue.
Regards

**Comment by Abdelaziz18003** [comment]
@tpoth I just released a new version containing forms components. I will release v1.0 soon. closing this issue.
