### ISSUE TITLE
Add to Quasar Awesome Repo

### ISSUE THREAD

**Issue by khuguet-tfg** [Abdelaziz18003/vscode-quasar-snippets#5]
Really nice set of code snippets for Quasar, but I noticed that it is not added to the [Quasar Awesome Repository](https://github.com/quasarframework/quasar-awesome#community-components-and-tools).  Adding it to the repo would definitely help to get your work more attention.  I can submit the PR if you would like, but it is your contribution so it would be best if it comes from you.  Let me know if you would like me to take any action.

Again great work here, it is really a time saver.  As awesome as Quasar is, it can be a bit verbose at times.

**Comment by Abdelaziz18003** [comment]
Hi @khuguet-tfg nice note from your part. You are right, I didn't pay attention to add it there. Definitely you have the permission to submit a PR and add it if you want since it is your suggestion. I really appreciate your contribution. Thank you very much.

**Comment by Abdelaziz18003** [comment]
I saw that it requires some description, so I will add it myself :) Thanks again for your good suggestion.

**Comment by Abdelaziz18003** [comment]
added https://github.com/quasarframework/quasar-awesome/pull/70.
